name: nexode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  nexode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /nexode') ||
      startsWith(github.event.comment.body, '/nexode')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run nexode
        uses: iamgrootns/Nexode/github@latest
        env:
          NEXODE_API_KEY: ${{ secrets.NEXODE_API_KEY }}
          NEXODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: nexode/claude-opus-4-5
